// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace ggg.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20230628180151_Lophoc")]
    partial class Lophoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("ggg.Models.Lophoc", b =>
                {
                    b.Property<string>("malop")
                        .HasColumnType("TEXT");

                    b.Property<string>("tenlop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("malop");

                    b.ToTable("Lophoc");
                });
#pragma warning restore 612, 618
        }
    }
}
