// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace ggg.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    partial class MvcMovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("ggg.Models.Lophoc", b =>
                {
                    b.Property<string>("malop")
                        .HasColumnType("TEXT");

                    b.Property<string>("tenlop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("malop");

                    b.ToTable("Lophoc");
                });

            modelBuilder.Entity("ggg.Models.Sinhvien", b =>
                {
                    b.Property<string>("masv")
                        .HasColumnType("TEXT");

                    b.Property<string>("hoten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("malop")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.Property<string>("diachi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("masv");

                    b.HasIndex("malop");

                    b.ToTable("Sinhvien");
                });

            modelBuilder.Entity("ggg.Models.Sinhvien", b =>
                {
                    b.HasOne("ggg.Models.Lophoc", "Lophoc")
                        .WithMany()
                        .HasForeignKey("malop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lophoc");
                });
#pragma warning restore 612, 618
        }
    }
}
